export const CAREER_LANGS=['ko','en-US','en-GB','zh-CN','ja','es','fr'];

const STATUS_LABELS={
  under_review:{ko:'채용 계획 검토 중','en-US':'Recruitment plan under review','en-GB':'Recruitment plan under review','zh-CN':'招聘计划审核中',ja:'採用計画を検討中',es:'Plan de contratación en revisión',fr:'Plan de recrutement à l’étude'},
  planned:{ko:'채용 예정','en-US':'Hiring planned','en-GB':'Hiring planned','zh-CN':'计划招聘',ja:'採用予定',es:'Contratación prevista',fr:'Recrutement prévu'},
  open:{ko:'채용 진행 중','en-US':'Hiring now','en-GB':'Hiring now','zh-CN':'正在招聘',ja:'募集中',es:'Contratación abierta',fr:'Recrutement en cours'},
  rolling:{ko:'수시 채용 검토','en-US':'Rolling hiring under review','en-GB':'Rolling hiring under review','zh-CN':'滚动招聘评估中',ja:'随時採用を検討',es:'Contratación continua en revisión',fr:'Recrutement continu à l’étude'},
  always:{ko:'상시 채용','en-US':'Open recruitment','en-GB':'Open recruitment','zh-CN':'长期招聘',ja:'常時採用',es:'Contratación permanente',fr:'Recrutement permanent'},
  none:{ko:'현재 채용 계획 없음','en-US':'No current hiring plan','en-GB':'No current hiring plan','zh-CN':'暂无招聘计划',ja:'現在採用予定なし',es:'Sin plan de contratación actual',fr:'Aucun recrutement prévu'}
};

const PERIOD_LABELS={
  tbd:{ko:'미정','en-US':'TBD','en-GB':'TBD','zh-CN':'待定',ja:'未定',es:'Por determinar',fr:'À déterminer'},
  h2_2026:{ko:'2026년 하반기','en-US':'H2 2026','en-GB':'H2 2026','zh-CN':'2026年下半年',ja:'2026年下半期',es:'Segundo semestre de 2026',fr:'2e semestre 2026'},
  q4_2026_q1_2027:{ko:'2026년 4분기 ~ 2027년 1분기','en-US':'Q4 2026 – Q1 2027','en-GB':'Q4 2026 – Q1 2027','zh-CN':'2026年第4季度至2027年第1季度',ja:'2026年第4四半期～2027年第1四半期',es:'T4 2026 – T1 2027',fr:'T4 2026 – T1 2027'},
  q1_2027:{ko:'2027년 1분기','en-US':'Q1 2027','en-GB':'Q1 2027','zh-CN':'2027年第1季度',ja:'2027年第1四半期',es:'T1 2027',fr:'T1 2027'},
  as_needed:{ko:'필요 직무 발생 시','en-US':'As roles become available','en-GB':'As roles become available','zh-CN':'根据岗位需求',ja:'必要な職種が発生した場合',es:'Cuando surjan vacantes',fr:'Selon les besoins en postes'}
};

const D={
  'flight-operations':{
    title:'Flight Operations',defaultStatusKey:'under_review',defaultPeriodKey:'h2_2026',
    locales:{
      ko:{koreanTitle:'운항 부문',summary:'항공편이 안전하고 정시에 출발·도착할 수 있도록 운항승무, 운항관리, 안전·품질과 네트워크 운영을 담당합니다.',duties:['운항승무 및 운항 기준 관리','운항관리·비행계획·운항통제','안전관리·품질보증·운항 리스크 관리','노선·스케줄·운항 자원 조정','지연·결항 등 비정상 운항 대응','운항 관련 법규·절차·매뉴얼 관리'],plannedRoles:'운항관리 · 안전/품질 · 네트워크 운영',recruitmentPlan:'운항 규모와 신규 노선 준비 상황에 맞춰 운항관리, 안전·품질, 네트워크 운영 인력의 단계적 채용을 검토합니다. 운항승무 채용은 기단 도입 및 운항계획 확정 이후 별도 공고합니다.'},
      'en-US':{koreanTitle:'Flight Operations',summary:'Keeps every flight safe and on schedule through flight crew standards, dispatch, safety, quality and network operations.',duties:['Flight crew and operating standards','Dispatch, flight planning and operations control','Safety management, quality assurance and operational risk','Route, schedule and operational resource coordination','Irregular operations response for delays and cancellations','Operational regulations, procedures and manuals'],plannedRoles:'Flight Dispatch · Safety/Quality · Network Operations',recruitmentPlan:'Hiring will be phased with fleet and network readiness, beginning with dispatch, safety/quality and network operations. Flight crew recruitment will be announced separately once fleet introduction and operating plans are confirmed.'},
      'en-GB':{koreanTitle:'Flight Operations',summary:'Keeps every flight safe and on schedule through flight crew standards, dispatch, safety, quality and network operations.',duties:['Flight crew and operating standards','Dispatch, flight planning and operations control','Safety management, quality assurance and operational risk','Route, schedule and operational resource coordination','Irregular operations response for delays and cancellations','Operational regulations, procedures and manuals'],plannedRoles:'Flight Dispatch · Safety/Quality · Network Operations',recruitmentPlan:'Hiring will be phased with fleet and network readiness, beginning with dispatch, safety/quality and network operations. Flight crew recruitment will be announced separately once fleet introduction and operating plans are confirmed.'},
      'zh-CN':{koreanTitle:'航班运行部门',summary:'负责飞行运行、签派、安全质量与航网运营，确保航班安全并尽可能准点运行。',duties:['飞行运行与运行标准管理','签派、飞行计划与运行控制','安全管理、质量保证与运行风险管理','航线、时刻与运行资源协调','延误、取消等非正常运行处置','运行法规、程序与手册管理'],plannedRoles:'运行签派 · 安全/质量 · 航网运营',recruitmentPlan:'将根据机队与新航线准备情况分阶段招聘签派、安全质量及航网运营人员。飞行机组招聘将在机队引进和运行计划确定后另行公告。'},
      ja:{koreanTitle:'運航部門',summary:'運航乗務、運航管理、安全・品質、ネットワーク運営を通じて、安全で定時性の高い運航を支えます。',duties:['運航乗務・運航基準の管理','運航管理・飛行計画・運航統制','安全管理・品質保証・運航リスク管理','路線・スケジュール・運航資源の調整','遅延・欠航などイレギュラー運航への対応','運航関連法規・手順・マニュアル管理'],plannedRoles:'運航管理 · 安全/品質 · ネットワーク運営',recruitmentPlan:'機材導入と路線準備に合わせ、運航管理、安全・品質、ネットワーク運営を段階的に採用します。運航乗務員は機材と運航計画の確定後に別途募集します。'},
      es:{koreanTitle:'Operaciones de vuelo',summary:'Garantiza operaciones seguras y puntuales mediante tripulaciones, despacho, seguridad, calidad y gestión de red.',duties:['Tripulaciones y estándares operativos','Despacho, planificación de vuelo y control operacional','Seguridad, calidad y gestión de riesgos operativos','Coordinación de rutas, horarios y recursos','Gestión de operaciones irregulares, retrasos y cancelaciones','Normativa, procedimientos y manuales de operaciones'],plannedRoles:'Despacho · Seguridad/Calidad · Operaciones de red',recruitmentPlan:'La contratación se realizará por fases según la preparación de la flota y la red, comenzando por despacho, seguridad/calidad y operaciones de red. Las vacantes de tripulación se publicarán por separado cuando se confirmen la flota y el plan operativo.'},
      fr:{koreanTitle:'Opérations aériennes',summary:'Assure des vols sûrs et ponctuels grâce aux équipages, au dispatch, à la sécurité, à la qualité et aux opérations réseau.',duties:['Équipages et standards opérationnels','Dispatch, planification des vols et contrôle des opérations','Sécurité, assurance qualité et gestion des risques','Coordination des routes, horaires et ressources','Gestion des opérations irrégulières, retards et annulations','Réglementation, procédures et manuels opérationnels'],plannedRoles:'Dispatch · Sécurité/Qualité · Opérations réseau',recruitmentPlan:'Le recrutement sera progressif selon la préparation de la flotte et du réseau, en commençant par le dispatch, la sécurité/qualité et les opérations réseau. Le recrutement des équipages sera annoncé séparément après confirmation de la flotte et du programme d’exploitation.'}
    }
  },
  'cabin-airport-service':{
    title:'Cabin & Airport Service',defaultStatusKey:'planned',defaultPeriodKey:'q4_2026_q1_2027',
    locales:{
      ko:{koreanTitle:'객실 · 공항서비스 부문',summary:'탑승 전 공항에서부터 기내 서비스와 도착 이후까지 고객 경험을 설계하고 운영합니다.',duties:['객실승무 및 객실 서비스 운영','공항 체크인·탑승·도착 서비스','고객경험 정책 및 서비스 품질관리','휠체어·유아·의료 등 특별지원 운영','수하물·환승·비정상 상황 고객 지원','서비스 교육·매뉴얼·현장 품질관리'],plannedRoles:'객실서비스 · 공항서비스 · 고객경험 · 특별지원',recruitmentPlan:'초기 운항 준비 일정에 맞춰 객실서비스와 공항서비스 인력을 우선 확보하고, 고객경험·특별지원 담당을 단계적으로 보강하는 계획입니다. 구체적인 모집 인원과 근무지는 확정 공고에서 안내합니다.'},
      'en-US':{koreanTitle:'Cabin & Airport Service',summary:'Designs and delivers the customer journey from airport check-in through the cabin experience and arrival.',duties:['Cabin crew and onboard service operations','Airport check-in, boarding and arrival services','Customer experience policy and service quality','Wheelchair, infant, medical and other special assistance','Baggage, transfer and irregular-operations customer support','Service training, manuals and field quality'],plannedRoles:'Cabin Service · Airport Service · Customer Experience · Special Assistance',recruitmentPlan:'Cabin and airport service roles will be prioritised for initial operations, followed by customer experience and special assistance roles. Final headcount and locations will be announced in official postings.'},
      'en-GB':{koreanTitle:'Cabin & Airport Service',summary:'Designs and delivers the customer journey from airport check-in through the cabin experience and arrival.',duties:['Cabin crew and onboard service operations','Airport check-in, boarding and arrival services','Customer experience policy and service quality','Wheelchair, infant, medical and other special assistance','Baggage, transfer and irregular-operations customer support','Service training, manuals and field quality'],plannedRoles:'Cabin Service · Airport Service · Customer Experience · Special Assistance',recruitmentPlan:'Cabin and airport service roles will be prioritised for initial operations, followed by customer experience and special assistance roles. Final headcount and locations will be announced in official postings.'},
      'zh-CN':{koreanTitle:'客舱与机场服务部门',summary:'从机场值机、登机到客舱服务和到达，全流程设计并运营旅客体验。',duties:['客舱乘务与客舱服务运营','机场值机、登机与到达服务','客户体验政策与服务质量管理','轮椅、婴幼儿、医疗等特殊协助','行李、中转及非正常运行旅客支持','服务培训、手册与现场质量管理'],plannedRoles:'客舱服务 · 机场服务 · 客户体验 · 特殊协助',recruitmentPlan:'初期运行准备阶段将优先配置客舱及机场服务人员，随后逐步补充客户体验与特殊协助岗位。最终人数和工作地点以正式招聘公告为准。'},
      ja:{koreanTitle:'客室・空港サービス部門',summary:'空港でのチェックインから機内サービス、到着後まで一貫したお客さま体験を設計・運営します。',duties:['客室乗務・機内サービス運営','空港チェックイン・搭乗・到着サービス','顧客体験方針・サービス品質管理','車いす・乳幼児・医療等の特別支援','手荷物・乗継・イレギュラー時の顧客支援','サービス教育・マニュアル・現場品質管理'],plannedRoles:'客室サービス · 空港サービス · 顧客体験 · 特別支援',recruitmentPlan:'運航開始準備に合わせて客室・空港サービスを優先採用し、その後、顧客体験・特別支援を段階的に強化します。募集人数と勤務地は正式公告で案内します。'},
      es:{koreanTitle:'Servicio de cabina y aeropuerto',summary:'Diseña y opera la experiencia del cliente desde el check-in hasta el servicio a bordo y la llegada.',duties:['Tripulación de cabina y servicio a bordo','Check-in, embarque y llegada en aeropuerto','Política de experiencia y calidad de servicio','Asistencia especial: movilidad, bebés y necesidades médicas','Apoyo en equipaje, conexiones y operaciones irregulares','Formación, manuales y control de calidad en campo'],plannedRoles:'Cabina · Aeropuerto · Experiencia del cliente · Asistencia especial',recruitmentPlan:'Se priorizarán los puestos de cabina y aeropuerto para el inicio de operaciones, seguidos de experiencia del cliente y asistencia especial. El número final de vacantes y ubicaciones se publicará oficialmente.'},
      fr:{koreanTitle:'Service cabine et aéroport',summary:'Conçoit et opère l’expérience client depuis l’enregistrement à l’aéroport jusqu’au service à bord et à l’arrivée.',duties:['Personnel cabine et service à bord','Enregistrement, embarquement et arrivée','Politique d’expérience client et qualité de service','Assistance spéciale : mobilité, nourrissons et besoins médicaux','Assistance bagages, correspondances et opérations irrégulières','Formation, manuels et qualité terrain'],plannedRoles:'Cabine · Aéroport · Expérience client · Assistance spéciale',recruitmentPlan:'Les postes cabine et aéroport seront prioritaires pour le lancement des opérations, puis les équipes expérience client et assistance spéciale seront renforcées. Les effectifs et lieux seront précisés dans les annonces officielles.'}
    }
  },
  'engineering-maintenance':{
    title:'Engineering & Maintenance',defaultStatusKey:'planned',defaultPeriodKey:'q1_2027',
    locales:{
      ko:{koreanTitle:'기술 · 정비 부문',summary:'항공기의 감항성과 신뢰성을 유지하기 위해 정비, 기술지원, 자재·품질과 신뢰성 업무를 수행합니다.',duties:['항공기 정비 계획 및 현장 정비 지원','기술문서·정비 프로그램·기술지원','항공기 신뢰성 분석 및 반복결함 관리','부품·자재·공구·재고 운영','정비 품질보증 및 협력업체 관리','기단 도입·개조·기술 프로젝트 지원'],plannedRoles:'정비기술 · 신뢰성 · 자재/품질',recruitmentPlan:'기단 도입과 정비지원 체계 구축 일정에 따라 정비기술, 신뢰성, 자재·품질 분야의 핵심 인력을 우선 채용하는 계획입니다. 자격증·경력 요건은 직무별 공고에서 구체화합니다.'},
      'en-US':{koreanTitle:'Engineering & Maintenance',summary:'Maintains aircraft airworthiness and reliability through maintenance, engineering support, materials, quality and reliability management.',duties:['Aircraft maintenance planning and line support','Technical documents, maintenance programmes and engineering support','Reliability analysis and recurring defect management','Parts, materials, tooling and inventory operations','Maintenance quality assurance and supplier oversight','Fleet introduction, modification and technical projects'],plannedRoles:'Maintenance Engineering · Reliability · Materials/Quality',recruitmentPlan:'Core maintenance engineering, reliability and materials/quality roles will be prioritised in line with fleet induction and maintenance-support readiness. Licence and experience requirements will be specified by position.'},
      'en-GB':{koreanTitle:'Engineering & Maintenance',summary:'Maintains aircraft airworthiness and reliability through maintenance, engineering support, materials, quality and reliability management.',duties:['Aircraft maintenance planning and line support','Technical documents, maintenance programmes and engineering support','Reliability analysis and recurring defect management','Parts, materials, tooling and inventory operations','Maintenance quality assurance and supplier oversight','Fleet introduction, modification and technical projects'],plannedRoles:'Maintenance Engineering · Reliability · Materials/Quality',recruitmentPlan:'Core maintenance engineering, reliability and materials/quality roles will be prioritised in line with fleet induction and maintenance-support readiness. Licence and experience requirements will be specified by position.'},
      'zh-CN':{koreanTitle:'工程与维修部门',summary:'通过维修、工程技术支持、航材质量与可靠性管理，保障航空器适航与可靠运行。',duties:['航空器维修计划与现场维修支持','技术文件、维修方案与工程支持','可靠性分析与重复故障管理','零部件、航材、工具与库存运营','维修质量保证与供应商管理','机队引进、改装与技术项目支持'],plannedRoles:'维修工程 · 可靠性 · 航材/质量',recruitmentPlan:'将根据机队引进和维修保障体系建设进度，优先招聘维修工程、可靠性及航材质量核心人员。执照与经验要求将在各岗位公告中明确。'},
      ja:{koreanTitle:'技術・整備部門',summary:'整備、技術支援、資材・品質、信頼性管理を通じて航空機の耐空性と信頼性を維持します。',duties:['航空機整備計画・現場整備支援','技術文書・整備プログラム・技術支援','信頼性分析・反復不具合管理','部品・資材・工具・在庫運営','整備品質保証・委託先管理','機材導入・改修・技術プロジェクト支援'],plannedRoles:'整備技術 · 信頼性 · 資材/品質',recruitmentPlan:'機材導入と整備支援体制の構築に合わせ、整備技術、信頼性、資材・品質の中核人材を優先採用します。資格・経験要件は職種別公告で明示します。'},
      es:{koreanTitle:'Ingeniería y mantenimiento',summary:'Mantiene la aeronavegabilidad y fiabilidad mediante mantenimiento, soporte técnico, materiales, calidad y gestión de fiabilidad.',duties:['Planificación de mantenimiento y soporte en línea','Documentación técnica, programas de mantenimiento y soporte de ingeniería','Análisis de fiabilidad y gestión de fallos repetitivos','Repuestos, materiales, herramientas e inventario','Aseguramiento de calidad y gestión de proveedores','Introducción de flota, modificaciones y proyectos técnicos'],plannedRoles:'Ingeniería de mantenimiento · Fiabilidad · Materiales/Calidad',recruitmentPlan:'Se priorizarán los perfiles clave de ingeniería de mantenimiento, fiabilidad y materiales/calidad según avance la incorporación de flota y el sistema de soporte. Los requisitos de licencia y experiencia se detallarán por puesto.'},
      fr:{koreanTitle:'Ingénierie et maintenance',summary:'Maintient la navigabilité et la fiabilité des avions grâce à la maintenance, au support technique, aux matériels, à la qualité et à la fiabilité.',duties:['Planification de maintenance et support en ligne','Documentation technique, programmes de maintenance et support d’ingénierie','Analyse de fiabilité et gestion des défauts récurrents','Pièces, matériels, outillage et stocks','Assurance qualité maintenance et gestion des fournisseurs','Introduction de flotte, modifications et projets techniques'],plannedRoles:'Ingénierie maintenance · Fiabilité · Matériels/Qualité',recruitmentPlan:'Les postes clés en ingénierie maintenance, fiabilité et matériels/qualité seront prioritaires selon l’avancement de l’introduction de flotte et du dispositif de support. Les exigences de licence et d’expérience seront précisées par poste.'}
    }
  },
  'digital-corporate':{
    title:'Digital & Corporate',defaultStatusKey:'rolling',defaultPeriodKey:'as_needed',
    locales:{
      ko:{koreanTitle:'디지털 · 경영지원 부문',summary:'예약·회원·운항 디지털 서비스를 만들고 재무, 인사, 마케팅, 상품과 전략을 통해 항공사 운영 기반을 구축합니다.',duties:['웹·앱·예약·회원 디지털 서비스 개발','데이터 분석·자동화·내부 시스템 운영','상품·운임·부가서비스 기획','재무·회계·구매·사업관리','인사·조직·채용·교육','마케팅·브랜드·홍보·전략 기획'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'디지털 서비스 개발과 사업 준비 과정에서 필요한 직무를 수시로 검토합니다. 프로젝트 우선순위에 따라 소프트웨어·데이터·상품 직무를 먼저 보강하고 경영지원 직무는 조직 확장 단계에 맞춰 채용합니다.'},
      'en-US':{koreanTitle:'Digital & Corporate',summary:'Builds reservation, membership and operations technology while establishing the airline’s finance, people, marketing, product and strategy capabilities.',duties:['Web, app, booking and membership product development','Data analytics, automation and internal systems','Product, fares and ancillary-service planning','Finance, accounting, procurement and business management','People, organisation, recruitment and learning','Marketing, brand, communications and strategy'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'Roles will be reviewed as digital products and business readiness evolve. Software, data and product capabilities will be strengthened first according to project priorities, with corporate functions expanding as the organisation grows.'},
      'en-GB':{koreanTitle:'Digital & Corporate',summary:'Builds reservation, membership and operations technology while establishing the airline’s finance, people, marketing, product and strategy capabilities.',duties:['Web, app, booking and membership product development','Data analytics, automation and internal systems','Product, fares and ancillary-service planning','Finance, accounting, procurement and business management','People, organisation, recruitment and learning','Marketing, brand, communications and strategy'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'Roles will be reviewed as digital products and business readiness evolve. Software, data and product capabilities will be strengthened first according to project priorities, with corporate functions expanding as the organisation grows.'},
      'zh-CN':{koreanTitle:'数字与职能部门',summary:'建设预订、会员与运行数字服务，并通过财务、人力、营销、产品和战略建立航空公司运营基础。',duties:['网站、App、预订与会员数字产品开发','数据分析、自动化与内部系统运营','产品、运价及附加服务规划','财务、会计、采购与经营管理','人力资源、组织、招聘与培训','营销、品牌、公关与战略规划'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'将根据数字服务开发和业务准备进度持续评估岗位需求。软件、数据和产品岗位将依据项目优先级优先补充，职能岗位则随组织扩张逐步招聘。'},
      ja:{koreanTitle:'デジタル・コーポレート部門',summary:'予約・会員・運航のデジタルサービスを構築し、財務、人事、マーケティング、商品、戦略で航空会社の運営基盤を整えます。',duties:['Web・アプリ・予約・会員デジタルサービス開発','データ分析・自動化・社内システム運営','商品・運賃・付帯サービス企画','財務・会計・購買・事業管理','人事・組織・採用・教育','マーケティング・ブランド・広報・戦略企画'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'デジタルサービス開発と事業準備に応じて必要職種を随時検討します。プロジェクト優先度に応じてソフトウェア・データ・商品を先に強化し、コーポレート職は組織拡大に合わせて採用します。'},
      es:{koreanTitle:'Digital y corporativo',summary:'Desarrolla tecnología de reservas, miembros y operaciones, y construye capacidades de finanzas, personas, marketing, producto y estrategia.',duties:['Desarrollo web, app, reservas y membresía','Analítica de datos, automatización y sistemas internos','Producto, tarifas y servicios complementarios','Finanzas, contabilidad, compras y gestión empresarial','Personas, organización, selección y formación','Marketing, marca, comunicación y estrategia'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'Las necesidades se revisarán a medida que avancen los productos digitales y la preparación del negocio. Se reforzarán primero software, datos y producto según las prioridades, y las funciones corporativas crecerán con la organización.'},
      fr:{koreanTitle:'Digital et fonctions corporate',summary:'Développe les services numériques de réservation, fidélité et opérations, ainsi que les capacités finance, RH, marketing, produit et stratégie.',duties:['Développement web, app, réservation et fidélité','Analyse de données, automatisation et systèmes internes','Produit, tarifs et services additionnels','Finance, comptabilité, achats et gestion','RH, organisation, recrutement et formation','Marketing, marque, communication et stratégie'],plannedRoles:'Software · Data · Product · Finance · HR · Marketing · Strategy',recruitmentPlan:'Les besoins seront revus au fil du développement des services numériques et de la préparation de l’activité. Les fonctions software, data et produit seront renforcées en priorité, puis les fonctions corporate avec la croissance de l’organisation.'}
    }
  }
};

export const CAREER_DEPARTMENTS=Object.fromEntries(Object.entries(D).map(([slug,d])=>[slug,{title:d.title,...d.locales.ko,hiringStatus:STATUS_LABELS[d.defaultStatusKey].ko,recruitmentPeriod:PERIOD_LABELS[d.defaultPeriodKey].ko,defaultStatusKey:d.defaultStatusKey,defaultPeriodKey:d.defaultPeriodKey}]));

const statusLegacy=Object.fromEntries(Object.entries(STATUS_LABELS).flatMap(([key,labels])=>Object.values(labels).map(label=>[label,key])));
const periodLegacy=Object.fromEntries(Object.entries(PERIOD_LABELS).flatMap(([key,labels])=>Object.values(labels).map(label=>[label,key])));

export const CAREER_STATUS_OPTIONS=Object.entries(STATUS_LABELS).map(([value,labels])=>({value,label:labels.ko}));
export const CAREER_PERIOD_OPTIONS=Object.entries(PERIOD_LABELS).map(([value,labels])=>({value,label:labels.ko}));
export const careerDocId=slug=>`careers-${slug}`;

export function currentCareerLanguage(){
  try{const stored=localStorage.getItem('stellaris-language');if(CAREER_LANGS.includes(stored))return stored;}catch(error){}
  const html=document.documentElement.lang;
  return CAREER_LANGS.includes(html)?html:'ko';
}

export function parseCareerNotice(slug,notice){
  const d=D[slug];if(!d)return null;let parsed={};
  try{parsed=notice?.body?JSON.parse(notice.body):{};}catch(error){parsed={};}
  const statusKey=STATUS_LABELS[parsed.hiringStatusKey]?parsed.hiringStatusKey:(statusLegacy[parsed.hiringStatus]||d.defaultStatusKey);
  const periodKey=PERIOD_LABELS[parsed.recruitmentPeriodKey]?parsed.recruitmentPeriodKey:(periodLegacy[parsed.recruitmentPeriod]||d.defaultPeriodKey);
  return {hiringStatusKey:statusKey,recruitmentPeriodKey:periodKey};
}

export function getCareerView(slug,lang='ko',managed=null){
  const d=D[slug];if(!d)return null;
  const locale=d.locales[CAREER_LANGS.includes(lang)?lang:'ko']||d.locales.ko;
  const state=managed||{hiringStatusKey:d.defaultStatusKey,recruitmentPeriodKey:d.defaultPeriodKey};
  return {title:d.title,...locale,hiringStatusKey:state.hiringStatusKey,recruitmentPeriodKey:state.recruitmentPeriodKey,hiringStatus:(STATUS_LABELS[state.hiringStatusKey]||STATUS_LABELS[d.defaultStatusKey])[lang]||STATUS_LABELS[d.defaultStatusKey].ko,recruitmentPeriod:(PERIOD_LABELS[state.recruitmentPeriodKey]||PERIOD_LABELS[d.defaultPeriodKey])[lang]||PERIOD_LABELS[d.defaultPeriodKey].ko};
}

export function careerNoticePayload(data){
  return JSON.stringify({version:2,hiringStatusKey:String(data.hiringStatusKey||'under_review'),recruitmentPeriodKey:String(data.recruitmentPeriodKey||'tbd')});
}