import { auth, db } from '../firebase-config.js';
import { browserLocalPersistence, onAuthStateChanged, setPersistence } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { collection, doc, getDocs, query, serverTimestamp, setDoc, where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { checkInWindow } from '../travel-service-core.js?v=20260817-digital-v1';

const M={
ko:{loading:'Star Miles 계정을 확인하고 있습니다…',signIn:'로그인 후 Star Miles를 확인하세요.',signInBody:'회원 계정으로 로그인하면 보유 마일과 등급, 예약을 통해 적립된 내역이 표시됩니다.',login:'로그인',book:'마일 적립 여행 예약',balance:'사용 가능 마일',tier:'회원 등급',earned:'확정 적립 마일',bookings:'마일리지 원장',progress:'다음 등급까지',history:'최근 마일리지 원장',none:'아직 마일리지 원장이 없습니다.',member:'회원번호',mile:'마일',max:'최고 등급입니다.'},
'en-US':{loading:'Checking your Star Miles account…',signIn:'Sign in to view your Star Miles.',signInBody:'Your balance, tier and mileage ledger from bookings will appear here.',login:'Sign in',book:'Book and earn miles',balance:'Available miles',tier:'Member tier',earned:'Confirmed miles',bookings:'Ledger entries',progress:'To the next tier',history:'Recent mileage ledger',none:'There is no mileage activity yet.',member:'Member number',mile:'miles',max:'You have reached the highest tier.'},
'en-GB':null,'zh-CN':null,ja:null,es:null,fr:null
};
M['en-GB']=M['en-US'];M['zh-CN']=M.ko;M.ja=M.ko;M.es=M['en-US'];M.fr=M['en-US'];
const lang=()=>{const value=localStorage.getItem('stellaris-language')||'ko';return M[value]?value:'ko'};
const t=key=>M[lang()][key]||M.ko[key];
const loading=document.querySelector('[data-miles-loading]'),guest=document.querySelector('[data-miles-guest]'),account=document.querySelector('[data-miles-account]');
function asDate(value){if(value?.toDate)return value.toDate();const date=new Date(value||0);return Number.isNaN(date.getTime())?new Date(0):date;}
function memberNumber(uid){let value=0;for(const c of uid)value=(value*31+c.charCodeAt(0))>>>0;return 'XS '+String(value).padStart(10,'0').slice(-10);}
function tierFor(miles){const tiers=[['STAR',0],['SILVER',20000],['GOLD',50000],['PLATINUM',100000],['STELLAR',200000]];let index=0;for(let i=0;i<tiers.length;i++)if(miles>=tiers[i][1])index=i;const current=tiers[index],next=tiers[index+1]||null;const progress=next?Math.max(0,Math.min(100,(miles-current[1])/(next[1]-current[1])*100)):100;return {name:current[0],next,progress};}
async function bookings(uid){const snap=await getDocs(query(collection(db,'bookings'),where('userId','==',uid)));return snap.docs.map(d=>({id:d.id,...d.data()}));}
async function syncLedger(user,items){for(const booking of items){const first=booking.segments?.[0],windowState=checkInWindow(booking),flown=Number.isFinite(windowState.departure)&&Date.now()>=windowState.departure,status=booking.status==='cancelled'?'cancelled':flown?'confirmed':'pending',amount=status==='cancelled'?0:Number(booking.milesEarned||0);try{await setDoc(doc(db,'mileageLedger',user.uid,'entries',booking.bookingRef||booking.id),{userId:user.uid,sourceBookingId:booking.id,bookingRef:booking.bookingRef||'',flightNumber:first?.flightNumber||booking.flightNumber||'',route:[booking.origin,booking.destination].filter(Boolean).join(' → '),amount,status,updatedAt:serverTimestamp()},{merge:true});}catch(error){}}}
async function ledger(uid){const snap=await getDocs(collection(db,'mileageLedger',uid,'entries'));return snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>asDate(b.updatedAt)-asDate(a.updatedAt));}
function setText(selector,value){const node=document.querySelector(selector);if(node)node.textContent=value;}
function translateStatic(){if(loading)loading.textContent=t('loading');const title=guest?.querySelector('h2');if(title)title.textContent=t('signIn');const body=guest?.querySelector('p:not(.eyebrow)');if(body)body.textContent=t('signInBody');const link=guest?.querySelector('.btn');if(link)link.textContent=t('login');const book=account?.querySelector('.miles-account-head .btn');if(book)book.textContent=t('book');setText('[data-label-balance]',t('balance'));setText('[data-label-tier]',t('tier'));setText('[data-label-earned]',t('earned'));setText('[data-label-bookings]',t('bookings'));setText('[data-progress-label]',t('progress'));setText('[data-history-title]',t('history'));}
async function renderUser(user){const bookingItems=await bookings(user.uid);await syncLedger(user,bookingItems);const entries=await ledger(user.uid);const confirmed=entries.filter(e=>e.status==='confirmed').reduce((s,e)=>s+Number(e.amount||0),0),used=entries.filter(e=>e.status==='used').reduce((s,e)=>s+Number(e.amount||0),0),available=Math.max(0,confirmed-used),tier=tierFor(confirmed);setText('[data-member-name]',user.displayName||user.email||'Stellaris Member');setText('[data-member-number]',t('member')+' · '+memberNumber(user.uid));setText('[data-mile-balance]',available.toLocaleString());setText('[data-total-earned]',confirmed.toLocaleString());setText('[data-booking-count]',String(entries.length));setText('[data-tier]',tier.name);setText('[data-tier-note]',tier.next?tier.next[0]+' · '+tier.next[1].toLocaleString()+' '+t('mile'):t('max'));setText('[data-next-tier]',tier.next?tier.next[0]:'STELLAR');setText('[data-progress-value]',tier.next?(tier.next[1]-confirmed).toLocaleString()+' '+t('mile'):'100%');const bar=document.querySelector('[data-tier-progress]');if(bar)bar.style.width=tier.progress+'%';const history=document.querySelector('[data-mile-history]');if(history){history.innerHTML=entries.length?entries.slice(0,15).map(item=>{const date=asDate(item.updatedAt),sign=item.status==='used'?'-':item.status==='cancelled'?'':'+';const status=({pending:'적립 예정',confirmed:'적립 확정',cancelled:'적립 취소',used:'사용'}[item.status]||item.status||'');return '<div class="miles-history-row"><time>'+new Intl.DateTimeFormat(lang(),{dateStyle:'medium'}).format(date)+'</time><div><strong>'+String(item.route||'STELLARIS')+'</strong><small>'+String(item.flightNumber||item.bookingRef||'')+' · '+status+'</small></div><b>'+sign+Number(item.amount||0).toLocaleString()+' '+t('mile')+'</b></div>';}).join(''):'<div class="miles-empty">'+t('none')+'</div>';}loading.hidden=true;guest.hidden=true;account.hidden=false;}
translateStatic();await setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,user=>{if(user)renderUser(user).catch(()=>{loading.textContent='Star Miles를 불러오지 못했습니다.';});else{loading.hidden=true;account.hidden=true;guest.hidden=false;}});window.addEventListener('stellaris:languagechange',()=>location.reload());
