import { db } from './firebase-config.js';
import { doc, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const DOC_ID='home_popup_config',MARK='[[STELLARIS_HOME_POPUP_V1]]';
let latest=null;
const lang=()=>{try{return localStorage.getItem('stellaris-language')==='en-US'?'en-US':'ko';}catch(error){return 'ko';}};
const L=(ko,en)=>lang()==='en-US'?(en||ko):ko;
function unpack(raw=''){const text=String(raw||'');if(!text.startsWith(MARK))return null;try{return JSON.parse(text.slice(MARK.length));}catch(error){return null;}}
function safeLink(value){const raw=String(value||'').trim();if(!raw)return '';try{const url=new URL(raw,new URL('./',import.meta.url));return ['http:','https:'].includes(url.protocol)?url.href:'';}catch(error){return '';}}
function sanitize(html=''){const doc=new DOMParser().parseFromString(`<div>${String(html||'')}</div>`,'text/html'),root=doc.body.firstElementChild,allowed=new Set(['P','BR','STRONG','B','EM','I','U','UL','OL','LI','DIV','SPAN','TABLE','THEAD','TBODY','TR','TH','TD','IMG','A','H2','H3','H4','BLOCKQUOTE']),styles=new Set(['font-size','font-family','font-weight','font-style','text-align','color']);[...root.querySelectorAll('*')].forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return;}[...el.attributes].forEach(attr=>{const n=attr.name.toLowerCase();if(n==='style'){const out=[];String(attr.value).split(';').forEach(rule=>{const at=rule.indexOf(':');if(at<0)return;const k=rule.slice(0,at).trim().toLowerCase(),v=rule.slice(at+1).trim();if(styles.has(k)&&v&&!/[{}<>]/.test(v))out.push(`${k}:${v}`);});if(out.length)el.setAttribute('style',out.join(';'));else el.removeAttribute('style');return;}if(el.tagName==='IMG'&&['src','alt'].includes(n))return;if(el.tagName==='A'&&['href','target','rel'].includes(n))return;el.removeAttribute(attr.name);});if(el.tagName==='IMG'){const u=safeLink(el.getAttribute('src'));if(!u){el.remove();return;}el.src=u;el.loading='lazy';}if(el.tagName==='A'){const u=safeLink(el.getAttribute('href'));if(!u){el.replaceWith(...el.childNodes);return;}el.href=u;el.target='_blank';el.rel='noopener noreferrer';}});return root.innerHTML;}
function dismissed(){try{return localStorage.getItem('stellaris-popup-dismissed-date')===new Date().toISOString().slice(0,10);}catch(error){return false;}}
function dismissToday(){try{localStorage.setItem('stellaris-popup-dismissed-date',new Date().toISOString().slice(0,10));}catch(error){}}
function ensureStyle(){if(document.querySelector('link[data-home-popup-style]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('./home-popup.css?v=20260820-v1',import.meta.url).href;link.dataset.homePopupStyle='true';document.head.appendChild(link);}
function close(){const host=document.querySelector('[data-managed-home-popup]');if(host)host.remove();document.body.style.overflow='';}
function render(){close();if(document.body.dataset.page!=='home'||!latest?.active||dismissed())return;const host=document.createElement('div');host.className='managed-home-popup';host.dataset.managedHomePopup='true';const mode=latest.mode==='image'?'image':'rich',href=safeLink(latest.linkUrl),label=L(latest.linkLabelKo||'자세히 보기',latest.linkLabelEn||'Learn more');let content='';if(mode==='image'){const image=safeLink(latest.imageUrl);if(!image)return;content=`<div class="managed-popup-image-wrap"><img src="${image}" alt="${L(latest.titleKo||'Stellaris promotion',latest.titleEn||'Stellaris promotion').replace(/"/g,'&quot;')}"></div>`;}else{content=`<div class="managed-popup-copy"><h2>${L(latest.titleKo||'',latest.titleEn||'').replace(/[<>]/g,'')}</h2><div class="managed-popup-rich">${sanitize(L(latest.htmlKo||'',latest.htmlEn||''))}</div></div>`;}host.innerHTML=`<section class="managed-popup-card ${mode}" role="dialog" aria-modal="true" aria-label="Stellaris promotion"><button type="button" class="managed-popup-close" data-popup-close aria-label="${L('닫기','Close')}">×</button>${content}<div class="managed-popup-actions"><button type="button" data-popup-day>${L('오늘 하루 보지 않기','Do not show again today')}</button>${href?`<a href="${href}">${label}</a>`:''}</div></section>`;document.body.append(host);document.body.style.overflow='hidden';host.querySelector('[data-popup-close]').addEventListener('click',close);host.querySelector('[data-popup-day]').addEventListener('click',()=>{dismissToday();close();});host.addEventListener('click',event=>{if(event.target===host)close();});}

ensureStyle();
try{onSnapshot(doc(db,'notices',DOC_ID),snap=>{latest=snap.exists()?unpack(snap.data().body):null;setTimeout(render,450);},()=>{});}catch(error){}
window.addEventListener('stellaris:languagechange',()=>setTimeout(render,0));
