import { db } from './firebase-config.js';
import { doc, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

function ensureStyle(href,marker){if(document.querySelector(`link[${marker}]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=new URL(href,import.meta.url).href;link.setAttribute(marker,'true');document.head.appendChild(link);}
ensureStyle('./site-content.css?v=20260817-digital-v1','data-site-content-style');
ensureStyle('./service-pages.css?v=20260817-digital-v1','data-service-pages-style');

const SEP='[[EN]]';
const DEFAULT_BANNER={active:true,text:'새로운 좌석 브랜드를 만나보세요 — CELESTIA · ASTRELIS · LUMINA · NOVA[[EN]]Meet our new cabin brands — CELESTIA · ASTRELIS · LUMINA · NOVA',linkLabel:'좌석 안내[[EN]]Seat guide',linkUrl:'seats/'};
const DEFAULT_HOME={heroTitle:'Beyond the horizon.',heroBody:'Stellaris Airlines와 함께 새로운 여정을 시작하세요.[[EN]]Start a new journey with Stellaris Airlines.',popupActive:false,popupTitle:'STELLARIS UPDATE',popupBody:'새로운 디지털 서비스를 확인해 보세요.[[EN]]Discover our latest digital services.',promotionTitle:'온라인 체크인[[EN]]Online check-in',promotionBody:'출발 24시간 전부터 온라인 체크인과 모바일 탑승권 발급이 가능합니다.[[EN]]Online check-in and mobile boarding passes are available from 24 hours before departure.',routeTitle:'추천 노선[[EN]]Featured routes',routeBody:'공개된 정기 운항 스케줄에서 다음 여정을 찾아보세요.[[EN]]Find your next journey in our published flight schedule.'};
let latestBanner=DEFAULT_BANNER,latestHome=DEFAULT_HOME;
function currentLanguage(){try{return localStorage.getItem('stellaris-language')==='en-US'?'en-US':'ko';}catch(error){return 'ko';}}
function localize(value){const raw=String(value??''),at=raw.indexOf(SEP);if(at<0)return raw;const ko=raw.slice(0,at),en=raw.slice(at+SEP.length);return currentLanguage()==='en-US'?(en||ko):ko;}
function retranslate(){queueMicrotask(()=>window.STELLARIS_AUTO_TRANSLATE?.translate?.());}
function safeHref(value){const raw=String(value||'').trim();if(!raw||/^javascript:/i.test(raw)||/^data:/i.test(raw))return '';try{return new URL(raw,new URL('./',import.meta.url)).href;}catch(error){return '';}}
function ensureBanner(){if(document.body.dataset.page!=='home'&&!document.body.classList.contains('page-home'))return null;let banner=document.querySelector('[data-home-announcement-banner]');if(banner)return banner;banner=document.createElement('aside');banner.className='home-announcement-banner';banner.dataset.homeAnnouncementBanner='true';banner.setAttribute('aria-label','Stellaris announcement');banner.innerHTML='<div class="shell-wide home-announcement-inner"><span data-home-banner-text></span><a data-home-banner-link hidden></a></div>';const header=document.querySelector('.site-header');if(header)header.before(banner);else document.body.prepend(banner);return banner;}
function renderBanner(data={}){latestBanner={...DEFAULT_BANNER,...data};const banner=ensureBanner();if(!banner)return;const config=latestBanner;banner.hidden=config.active===false;const text=banner.querySelector('[data-home-banner-text]');if(text)text.textContent=localize(config.text||DEFAULT_BANNER.text);const link=banner.querySelector('[data-home-banner-link]');const href=safeHref(config.linkUrl);const label=localize(config.linkLabel);if(link&&href&&label){link.hidden=false;link.href=href;link.textContent=label+' →';}else if(link){link.hidden=true;link.removeAttribute('href');link.textContent='';}retranslate();}
function ensureHomeStrip(){if(document.body.dataset.page!=='home'&&!document.body.classList.contains('page-home'))return null;let strip=document.querySelector('[data-home-experience-strip]');if(strip)return strip;strip=document.createElement('section');strip.className='home-experience-strip';strip.dataset.homeExperienceStrip='true';strip.innerHTML='<div class="shell"><div><strong data-home-promo-title></strong><p data-home-promo-body></p></div><div><strong data-home-route-title></strong><p data-home-route-body></p></div></div>';const hero=document.querySelector('.home-hero');if(hero)hero.insertAdjacentElement('afterend',strip);return strip;}
function ensurePopup(){let popup=document.querySelector('[data-home-experience-popup]');if(popup)return popup;popup=document.createElement('aside');popup.className='home-experience-popup';popup.dataset.homeExperiencePopup='true';popup.innerHTML='<button type="button" aria-label="닫기" data-home-popup-close>×</button><p class="eyebrow" data-home-popup-title></p><p data-home-popup-body></p>';popup.querySelector('[data-home-popup-close]').addEventListener('click',()=>{popup.hidden=true;sessionStorage.setItem('stellaris-home-popup-dismissed','1');});document.body.appendChild(popup);return popup;}
function renderHomeExperience(data={}){latestHome={...DEFAULT_HOME,...data};if(document.body.dataset.page!=='home'&&!document.body.classList.contains('page-home'))return;const config=latestHome;const heroTitle=document.querySelector('.home-hero .hero-copy h1');const heroBody=document.querySelector('.home-hero .hero-copy > p:not(.eyebrow)');if(heroTitle&&config.heroTitle)heroTitle.textContent=localize(config.heroTitle);if(heroBody&&config.heroBody)heroBody.textContent=localize(config.heroBody);const strip=ensureHomeStrip();if(strip){strip.querySelector('[data-home-promo-title]').textContent=localize(config.promotionTitle||'');strip.querySelector('[data-home-promo-body]').textContent=localize(config.promotionBody||'');strip.querySelector('[data-home-route-title]').textContent=localize(config.routeTitle||'');strip.querySelector('[data-home-route-body]').textContent=localize(config.routeBody||'');}const popup=ensurePopup();if(popup){popup.querySelector('[data-home-popup-title]').textContent=localize(config.popupTitle||'');popup.querySelector('[data-home-popup-body]').textContent=localize(config.popupBody||'');popup.hidden=config.popupActive!==true||sessionStorage.getItem('stellaris-home-popup-dismissed')==='1';}retranslate();}

renderBanner(DEFAULT_BANNER);renderHomeExperience(DEFAULT_HOME);
try{onSnapshot(doc(db,'siteContent','homeBanner'),snapshot=>renderBanner(snapshot.exists()?snapshot.data():DEFAULT_BANNER),()=>renderBanner(DEFAULT_BANNER));}catch(error){renderBanner(DEFAULT_BANNER);}
try{onSnapshot(doc(db,'siteContent','homeExperience'),snapshot=>renderHomeExperience(snapshot.exists()?snapshot.data():DEFAULT_HOME),()=>renderHomeExperience(DEFAULT_HOME));}catch(error){renderHomeExperience(DEFAULT_HOME);}
window.addEventListener('stellaris:languagechange',()=>{renderBanner(latestBanner);renderHomeExperience(latestHome);});
