(()=>{
'use strict';
const I18N={
ko:{origin:'출발 공항',destination:'도착 공항',refresh:'기상정보 새로고침',loading:'공항 기상정보를 불러오는 중입니다…',normal:'기상 양호',watch:'기상 주의',alert:'운항 확인 필요',updated:'업데이트',temp:'기온',feels:'체감',precip:'강수',gust:'돌풍',visibility:'시정',wind:'바람',good:'현재 공항 기상에서 뚜렷한 운항 위험 신호가 감지되지 않았습니다.',watchMsg:'강수·강풍·저시정 가능성이 있습니다. 운항 변경 여부를 출발 전에 확인하세요.',alertMsg:'강한 돌풍, 많은 강수 또는 매우 낮은 시정이 감지되었습니다. 실제 운항 상태를 반드시 확인하세요.',disclaimer:'이 표시는 공개 기상자료를 이용한 자동 참고 정보이며 실제 지연·결항 여부를 확정하지 않습니다. 최종 운항 상태는 항공사 공지와 공항 안내를 확인하세요.',error:'기상정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.',clear:'맑음',cloudy:'흐림',fog:'안개',rain:'비',snow:'눈',storm:'뇌우'},
'en-US':{origin:'Departure airport',destination:'Arrival airport',refresh:'Refresh weather',loading:'Loading airport weather…',normal:'Weather favourable',watch:'Weather advisory',alert:'Check flight status',updated:'Updated',temp:'Temperature',feels:'Feels like',precip:'Precipitation',gust:'Gusts',visibility:'Visibility',wind:'Wind',good:'No significant weather-related operating risk is currently detected at either airport.',watchMsg:'Rain, strong wind or low visibility may affect operations. Check your flight before departure.',alertMsg:'Severe gusts, heavy precipitation or very low visibility detected. Verify the actual flight status.',disclaimer:'This automated advisory uses public weather data and does not confirm delays or cancellations. Check airline and airport notices for the final status.',error:'Weather data is unavailable. Please try again shortly.',clear:'Clear',cloudy:'Cloudy',fog:'Fog',rain:'Rain',snow:'Snow',storm:'Thunderstorm'}};
I18N['en-GB']=I18N['en-US']; I18N['zh-CN']={...I18N['en-US'],origin:'出发机场',destination:'到达机场',refresh:'刷新天气',loading:'正在加载机场天气…',normal:'天气良好',watch:'天气注意',alert:'请确认航班状态',updated:'更新时间',disclaimer:'此自动提示使用公开天气数据，不代表实际延误或取消。请以航空公司和机场公告为准。'};
I18N.ja={...I18N['en-US'],origin:'出発空港',destination:'到着空港',refresh:'気象情報を更新',loading:'空港の気象情報を読み込み中…',normal:'気象良好',watch:'気象注意',alert:'運航状況を確認',updated:'更新',disclaimer:'公開気象データによる自動参考情報であり、遅延・欠航を確定するものではありません。航空会社と空港の案内をご確認ください。'};
I18N.es={...I18N['en-US'],origin:'Aeropuerto de salida',destination:'Aeropuerto de llegada',refresh:'Actualizar tiempo',loading:'Cargando el tiempo…',normal:'Tiempo favorable',watch:'Aviso meteorológico',alert:'Compruebe el vuelo',updated:'Actualizado',disclaimer:'Este aviso automático usa datos meteorológicos públicos y no confirma retrasos ni cancelaciones.'};
I18N.fr={...I18N['en-US'],origin:'Aéroport de départ',destination:"Aéroport d’arrivée",refresh:'Actualiser la météo',loading:'Chargement de la météo…',normal:'Météo favorable',watch:'Vigilance météo',alert:'Vérifier le vol',updated:'Actualisé',disclaimer:"Cet avis automatique utilise des données météo publiques et ne confirme ni retard ni annulation."};
const airports={
ICN:['인천','Incheon',37.4602,126.4407],GMP:['김포','Gimpo',37.5583,126.7906],CJU:['제주','Jeju',33.5104,126.4914],PUS:['부산','Busan',35.1795,128.9382],
NYC:['뉴욕','New York',40.6413,-73.7781],SEA:['시애틀','Seattle',47.4502,-122.3088],LAX:['로스앤젤레스','Los Angeles',33.9416,-118.4085],HNL:['호놀룰루','Honolulu',21.3187,-157.9225],
THT:['타히티','Tahiti',-17.5537,-149.607],SYD:['시드니','Sydney',-33.9399,151.1753],LHR:['런던','London',51.4700,-0.4543],CDG:['파리','Paris',49.0097,2.5479],STR:['산토리니','Santorini',36.3992,25.4793],DXB:['두바이','Dubai',25.2532,55.3657]};
const root=document.querySelector('[data-weather-app]'); if(!root)return;
const getLang=()=>{const v=localStorage.getItem('stellaris-language')||document.documentElement.lang||'ko';return I18N[v]?v:'ko'};
const t=k=>(I18N[getLang()]||I18N.ko)[k]||I18N['en-US'][k]||k;
const select=(name,value)=>'<label class="weather-field"><span data-weather-label="'+name+'">'+t(name)+'</span><select data-'+name+'>'+Object.entries(airports).map(([code,a])=>'<option value="'+code+'"'+(code===value?' selected':'')+'>'+code+' · '+(getLang()==='ko'?a[0]:a[1])+'</option>').join('')+'</select></label>';
root.innerHTML='<div class="weather-controls">'+select('origin','ICN')+'<div class="weather-route-arrow">→</div>'+select('destination','NYC')+'<button class="weather-refresh" type="button">'+t('refresh')+'</button></div><div data-weather-output><p>'+t('loading')+'</p></div><p class="weather-disclaimer" data-weather-disclaimer>'+t('disclaimer')+'</p>';
const output=root.querySelector('[data-weather-output]'),button=root.querySelector('.weather-refresh');
const weatherText=code=>code===0?[t('clear'),'☀️']:code<=3?[t('cloudy'),'☁️']:code<=48?[t('fog'),'🌫️']:code<=67||code<=82?[t('rain'),'🌧️']:code<=77||code<=86?[t('snow'),'🌨️']:[t('storm'),'⛈️'];
const risk=c=>{const gust=c.wind_gusts_10m||0,precip=c.precipitation||0,vis=c.visibility??10000,code=c.weather_code||0;if(gust>=55||precip>=15||vis<1000||code>=95)return 2;if(gust>=35||precip>=5||vis<3000||code>=51)return 1;return 0};
const card=(code,c)=>{const a=airports[code],w=weatherText(c.weather_code||0);return '<article class="airport-weather"><header><div><span class="airport-code">'+code+'</span><h3>'+(getLang()==='ko'?a[0]:a[1])+'</h3></div><span class="weather-icon" aria-hidden="true">'+w[1]+'</span></header><div class="weather-primary"><strong>'+Math.round(c.temperature_2m)+'°</strong><span>'+w[0]+'</span></div><div class="weather-metrics"><div><small>'+t('feels')+'</small><b>'+Math.round(c.apparent_temperature)+'°C</b></div><div><small>'+t('precip')+'</small><b>'+c.precipitation+' mm</b></div><div><small>'+t('gust')+'</small><b>'+Math.round(c.wind_gusts_10m)+' km/h</b></div><div><small>'+t('visibility')+'</small><b>'+((c.visibility??0)/1000).toFixed(1)+' km</b></div><div><small>'+t('wind')+'</small><b>'+Math.round(c.wind_speed_10m)+' km/h</b></div><div><small>'+t('temp')+'</small><b>'+Math.round(c.temperature_2m)+'°C</b></div></div></article>'};
async function load(){
button.disabled=true;button.textContent=t('loading');output.innerHTML='<p>'+t('loading')+'</p>';
const from=root.querySelector('[data-origin]').value,to=root.querySelector('[data-destination]').value;
try{const list=[from,to].map(code=>{const a=airports[code];const u=new URL('https://api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:a[2],longitude:a[3],current:'temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_gusts_10m,visibility',wind_speed_unit:'kmh',timezone:'auto'});return fetch(u).then(r=>{if(!r.ok)throw Error(r.status);return r.json()})});const data=await Promise.all(list);const level=Math.max(risk(data[0].current),risk(data[1].current));const state=level===2?'alert':level===1?'watch':'normal',msg=level===2?'alertMsg':level===1?'watchMsg':'good';output.innerHTML='<div class="weather-summary"><span class="weather-state '+(level===1?'watch':level===2?'alert':'')+'">'+t(state)+'</span><span class="weather-updated">'+t('updated')+' · '+new Intl.DateTimeFormat(getLang(),{dateStyle:'medium',timeStyle:'short'}).format(new Date())+'</span></div><div class="airport-weather-grid">'+card(from,data[0].current)+card(to,data[1].current)+'</div><p class="weather-advisory">'+t(msg)+'</p>';}catch(e){output.innerHTML='<p class="weather-error">'+t('error')+'</p>';}finally{button.disabled=false;button.textContent=t('refresh')}}
button.addEventListener('click',load);root.querySelectorAll('select').forEach(x=>x.addEventListener('change',load));window.addEventListener('stellaris:languagechange',()=>location.reload());load();
})();