import { db } from '../firebase-config.js';
import { collection, doc, increment, onSnapshot, orderBy, query, updateDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const host=document.querySelector('[data-notice-list]'),searchInput=document.querySelector('[data-notice-search]'),clearButton=document.querySelector('[data-notice-search-clear]'),pagination=document.querySelector('[data-notice-pagination]');
const PAGE_SIZE=10;let allItems=[],page=1;
const asDate=value=>{try{const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?null:d;}catch(error){return null;}};
const formatDate=value=>{const d=asDate(value);return d?new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d):'';};
const noticeType=item=>item.category==='중요'||item.pinned?'중요':'일반';
function isVisible(item){if(item.status==='draft')return false;const now=Date.now(),start=asDate(item.publishStart||item.publishedAt),end=asDate(item.publishEnd);if(start&&start.getTime()>now)return false;if(end&&end.getTime()<now)return false;return true;}
function filtered(){const term=String(searchInput?.value||'').trim().toLowerCase();let items=allItems.filter(isVisible);if(term)items=items.filter(item=>[item.title,item.body,item.author,item.category].some(v=>String(v||'').toLowerCase().includes(term)));return items.sort((a,b)=>Number(noticeType(b)==='중요')-Number(noticeType(a)==='중요')||((asDate(b.publishStart||b.publishedAt)?.getTime()||0)-(asDate(a.publishStart||a.publishedAt)?.getTime()||0)));}
function setDetailUrl(id){const url=new URL(location.href);if(id)url.searchParams.set('id',id);else url.searchParams.delete('id');history.replaceState(null,'',url);}
async function countView(item){const key=`stellaris-notice-view-${item.id}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');try{await updateDoc(doc(db,'notices',item.id),{views:increment(1)});}catch(error){}}
function buildEntry(item,forceOpen=false){const type=noticeType(item),wrapper=document.createElement('article');wrapper.className='notice-entry'+(type==='중요'?' is-important':'');wrapper.dataset.noticeId=item.id;const row=document.createElement('div');row.className='notice-row';row.setAttribute('role','row');const typeCell=document.createElement('div');typeCell.className='notice-cell notice-type-cell';typeCell.dataset.label='구분';const badge=document.createElement('span');badge.className='notice-type '+(type==='중요'?'important':'normal');badge.textContent=type;typeCell.append(badge);const titleCell=document.createElement('div');titleCell.className='notice-cell notice-title-cell';titleCell.dataset.label='제목';const titleButton=document.createElement('button');titleButton.type='button';titleButton.className='notice-title-button';titleButton.textContent=item.title||'제목 없음';titleCell.append(titleButton);const author=document.createElement('div');author.className='notice-cell notice-author';author.dataset.label='작성자';author.textContent=item.author||'STELLARIS AIRLINES';const date=document.createElement('time');date.className='notice-cell notice-date';date.dataset.label='날짜';date.textContent=formatDate(item.publishStart||item.publishedAt||item.updatedAt);row.append(typeCell,titleCell,author,date);const detail=document.createElement('div');detail.className='notice-detail';detail.hidden=true;const body=document.createElement('p');body.textContent=item.body||'';const meta=document.createElement('small');meta.className='notice-detail-meta';meta.textContent=`조회 ${Number(item.views||0).toLocaleString()} · ${item.status||'published'}`;detail.append(body,meta);const toggle=open=>{detail.hidden=!open;titleButton.setAttribute('aria-expanded',String(open));wrapper.classList.toggle('is-open',open);if(open){setDetailUrl(item.id);void countView(item);}else if(new URL(location.href).searchParams.get('id')===item.id)setDetailUrl('');};titleButton.addEventListener('click',()=>toggle(detail.hidden));wrapper.append(row,detail);if(forceOpen)queueMicrotask(()=>toggle(true));return wrapper;}
function renderPagination(total){if(!pagination)return;const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(page,pages);pagination.innerHTML=Array.from({length:pages},(_,i)=>`<button type="button" class="${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');pagination.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{page=Number(button.dataset.page);render();scrollTo({top:document.querySelector('.notice-shell')?.offsetTop||0,behavior:'smooth'});}));}
function render(){if(!host)return;const items=filtered(),detailId=new URL(location.href).searchParams.get('id');if(detailId){const idx=items.findIndex(i=>i.id===detailId);if(idx>=0)page=Math.floor(idx/PAGE_SIZE)+1;}if(!items.length){host.innerHTML='<p class="notice-empty">검색 조건에 맞는 공지사항이 없습니다.</p>';renderPagination(0);return;}const start=(page-1)*PAGE_SIZE,slice=items.slice(start,start+PAGE_SIZE);host.innerHTML='';slice.forEach(item=>host.appendChild(buildEntry(item,item.id===detailId)));renderPagination(items.length);}
searchInput?.addEventListener('input',()=>{page=1;setDetailUrl('');render();});clearButton?.addEventListener('click',()=>{if(searchInput)searchInput.value='';page=1;setDetailUrl('');render();});
try{onSnapshot(query(collection(db,'notices'),orderBy('publishedAt','desc')),snapshot=>{allItems=snapshot.docs.map(d=>({id:d.id,...d.data()}));render();},error=>{console.warn(error);host.innerHTML='<p class="notice-empty">공지사항을 불러오지 못했습니다.</p>';});}catch(error){host.innerHTML='<p class="notice-empty">공지사항을 불러오지 못했습니다.</p>';}
