import { db } from '../firebase-config.js';
import { collection, onSnapshot, orderBy, query } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const host=document.querySelector('[data-notice-list]'),searchInput=document.querySelector('[data-notice-search]'),clearButton=document.querySelector('[data-notice-search-clear]'),pagination=document.querySelector('[data-notice-pagination]');
const PAGE_SIZE=10,NEW_MS=3*24*60*60*1000,MARK='[[STELLARIS_BILINGUAL_V1]]';let allItems=[],page=1;
const lang=()=>{try{return localStorage.getItem('stellaris-language')==='en-US'?'en-US':'ko';}catch(error){return 'ko';}};
const L=(ko,en)=>lang()==='en-US'?en:ko;
const asDate=value=>{try{const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?null:d;}catch(error){return null;}};
const formatDate=value=>{const d=asDate(value);return d?new Intl.DateTimeFormat(lang()==='en-US'?'en-US':'ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d):'';};
function safeUrl(value){const raw=String(value||'').trim();if(!raw)return '';try{const url=new URL(raw,location.href);return ['http:','https:','mailto:'].includes(url.protocol)?url.href:'';}catch(error){return '';}}
function sanitize(html=''){const doc=new DOMParser().parseFromString(`<div>${String(html||'')}</div>`,'text/html'),root=doc.body.firstElementChild,allowed=new Set(['P','BR','STRONG','B','EM','I','U','UL','OL','LI','DIV','SPAN','TABLE','THEAD','TBODY','TR','TH','TD','IMG','A','H2','H3','H4','BLOCKQUOTE']),styles=new Set(['font-size','font-family','font-weight','font-style','text-align','color']);[...root.querySelectorAll('*')].forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return;}[...el.attributes].forEach(attr=>{const n=attr.name.toLowerCase();if(n==='style'){const out=[];String(attr.value).split(';').forEach(rule=>{const at=rule.indexOf(':');if(at<0)return;const k=rule.slice(0,at).trim().toLowerCase(),v=rule.slice(at+1).trim();if(styles.has(k)&&v&&!/[{}<>]/.test(v))out.push(`${k}:${v}`);});if(out.length)el.setAttribute('style',out.join(';'));else el.removeAttribute('style');return;}if(el.tagName==='IMG'&&['src','alt'].includes(n))return;if(el.tagName==='A'&&['href','target','rel'].includes(n))return;el.removeAttribute(attr.name);});if(el.tagName==='IMG'){const u=safeUrl(el.getAttribute('src'));if(!u){el.remove();return;}el.src=u;el.loading='lazy';}if(el.tagName==='A'){const u=safeUrl(el.getAttribute('href'));if(!u){el.replaceWith(...el.childNodes);return;}el.href=u;if(/^https?:/i.test(u)){el.target='_blank';el.rel='noopener noreferrer';}}});return root.innerHTML;}
function textOnly(html=''){const div=document.createElement('div');div.innerHTML=sanitize(html);return div.textContent||'';}
function unpackBody(value){const raw=String(value||'');if(!raw.startsWith(MARK))return {ko:raw,enTitle:'',en:''};try{const data=JSON.parse(raw.slice(MARK.length));return {ko:String(data.ko||''),enTitle:String(data.enTitle||''),en:String(data.en||'')};}catch(error){return {ko:raw,enTitle:'',en:''};}}
function localized(item){const packed=unpackBody(item.body);if(lang()==='en-US')return {title:packed.enTitle||item.title||'',body:packed.en||packed.ko||''};return {title:item.title||'',body:packed.ko||String(item.body||'')};}
function isVisible(item){if(item.status==='draft'||item.title==='HOME_POPUP_CONFIG')return false;const now=Date.now(),start=asDate(item.publishStart||item.publishedAt),end=asDate(item.publishEnd);if(start&&start.getTime()>now)return false;if(end&&end.getTime()<now)return false;return true;}
function registrationDate(item){return asDate(item.publishedAt||item.publishStart||item.updatedAt);}
function isNew(item){const date=registrationDate(item);if(!date)return false;const age=Date.now()-date.getTime();return age>=0&&age<=NEW_MS;}
function filtered(){const term=String(searchInput?.value||'').trim().toLowerCase();let items=allItems.filter(isVisible);if(term)items=items.filter(item=>{const local=localized(item),packed=unpackBody(item.body);return [local.title,textOnly(local.body),item.title,packed.enTitle,textOnly(packed.en),textOnly(packed.ko),item.author].some(value=>String(value||'').toLowerCase().includes(term));});return items.sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))||((registrationDate(b)?.getTime()||0)-(registrationDate(a)?.getTime()||0)));}
function setDetailUrl(id){const url=new URL(location.href);if(id)url.searchParams.set('id',id);else url.searchParams.delete('id');history.replaceState(null,'',url);}
function badges(item){const wrap=document.createElement('span');wrap.className='notice-badges-v3';if(isNew(item)){const badge=document.createElement('span');badge.className='notice-badge-v3 new';badge.textContent='NEW';wrap.append(badge);}const notice=document.createElement('span');notice.className='notice-badge-v3'+(item.pinned?' important':'');notice.textContent=L('공지','NOTICE');wrap.append(notice);return wrap;}
function buildEntry(item,forceOpen=false){
  const local=localized(item),wrapper=document.createElement('article');wrapper.className='notice-entry'+(item.pinned?' is-important':'');wrapper.dataset.noticeId=item.id;
  const row=document.createElement('div');row.className='notice-row';row.setAttribute('role','row');
  const typeCell=document.createElement('div');typeCell.className='notice-cell notice-type-cell';typeCell.dataset.label=L('구분','Type');typeCell.append(badges(item));
  const titleCell=document.createElement('div');titleCell.className='notice-cell notice-title-cell';titleCell.dataset.label=L('제목','Title');const titleButton=document.createElement('button');titleButton.type='button';titleButton.className='notice-title-button';titleButton.textContent=local.title||L('제목 없음','Untitled');titleCell.append(titleButton);
  const author=document.createElement('div');author.className='notice-cell notice-author';author.dataset.label=L('작성자','Author');author.textContent=item.author||'STELLARIS AIRLINES';
  const date=document.createElement('time');date.className='notice-cell notice-date';date.dataset.label=L('등록일','Posted');date.textContent=formatDate(registrationDate(item));
  row.append(typeCell,titleCell,author,date);
  const detail=document.createElement('div');detail.className='notice-detail notice-rich-detail';detail.hidden=true;detail.innerHTML=sanitize(local.body||'');
  const toggle=open=>{detail.hidden=!open;titleButton.setAttribute('aria-expanded',String(open));wrapper.classList.toggle('is-open',open);if(open)setDetailUrl(item.id);else if(new URL(location.href).searchParams.get('id')===item.id)setDetailUrl('');};titleButton.addEventListener('click',()=>toggle(detail.hidden));wrapper.append(row,detail);if(forceOpen)queueMicrotask(()=>toggle(true));return wrapper;
}
function renderPagination(total){if(!pagination)return;const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));page=Math.min(page,pages);pagination.innerHTML=Array.from({length:pages},(_,i)=>`<button type="button" class="${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');pagination.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{page=Number(button.dataset.page);render();scrollTo({top:document.querySelector('.notice-shell')?.offsetTop||0,behavior:'smooth'});}));}
function render(){if(!host)return;const items=filtered(),detailId=new URL(location.href).searchParams.get('id');if(detailId){const idx=items.findIndex(item=>item.id===detailId);if(idx>=0)page=Math.floor(idx/PAGE_SIZE)+1;}if(!items.length){host.innerHTML=`<p class="notice-empty">${L('검색 조건에 맞는 공지사항이 없습니다.','No notices match your search.')}</p>`;renderPagination(0);return;}const start=(page-1)*PAGE_SIZE,slice=items.slice(start,start+PAGE_SIZE);host.innerHTML='';slice.forEach(item=>host.appendChild(buildEntry(item,item.id===detailId)));renderPagination(items.length);}
searchInput?.addEventListener('input',()=>{page=1;setDetailUrl('');render();});clearButton?.addEventListener('click',()=>{if(searchInput)searchInput.value='';page=1;setDetailUrl('');render();});
window.addEventListener('stellaris:languagechange',()=>{page=1;render();});
try{onSnapshot(query(collection(db,'notices'),orderBy('publishedAt','desc')),snapshot=>{allItems=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));render();},error=>{console.warn(error);host.innerHTML=`<p class="notice-empty">${L('공지사항을 불러오지 못했습니다.','Notices could not be loaded.')}</p>`;});}catch(error){host.innerHTML=`<p class="notice-empty">${L('공지사항을 불러오지 못했습니다.','Notices could not be loaded.')}</p>`;}
