import { auth, db } from '../firebase-config.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { doc, getDoc, serverTimestamp, setDoc, Timestamp, updateDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { CAREER_DEPARTMENTS, careerDocId, careerNoticePayload, parseCareerNotice } from '../careers/career-data.js?v=20260817-careers-v1';
const ADMIN_EMAILS=new Set(['stellarisairlines@gmail.com','stellaris.web.dev@gmail.com']);
const isAdmin=user=>Boolean(user&&ADMIN_EMAILS.has(String(user.email||'').toLowerCase()));
let panel=null,form=null,statusEl=null;
function ensurePanel(){if(panel)return panel;const consoleHost=document.querySelector('[data-admin-console]');if(!consoleHost)return null;panel=document.createElement('section');panel.className='admin-panel';panel.id='career-manager';panel.innerHTML=`<div class="admin-panel-head"><div><p class="eyebrow">CAREER MANAGER</p><h2>부서 · 채용 계획 관리</h2></div><a href="../careers/" target="_blank" rel="noopener">채용 페이지 보기 →</a></div><form data-career-form class="admin-form"><div class="admin-grid"><label>부서<select name="department" required><option value="flight-operations">Flight Operations</option><option value="cabin-airport-service">Cabin &amp; Airport Service</option><option value="engineering-maintenance">Engineering &amp; Maintenance</option><option value="digital-corporate">Digital &amp; Corporate</option></select></label><label>한글 부서명<input name="koreanTitle" maxlength="80" required></label></div><label>부서 소개<textarea name="summary" rows="3" maxlength="800" required></textarea></label><label>주요 업무 <small>한 줄에 하나씩 입력</small><textarea name="duties" rows="7" maxlength="2500" required></textarea></label><div class="admin-grid"><label>채용 상태<select name="hiringStatus"><option>채용 계획 검토 중</option><option>채용 예정</option><option>채용 진행 중</option><option>수시 채용 검토</option><option>상시 채용</option><option>현재 채용 계획 없음</option></select></label><label>예상 채용 시기<input name="recruitmentPeriod" maxlength="120"></label></div><label>예정 직무<input name="plannedRoles" maxlength="400"></label><label>채용 계획 설명<textarea name="recruitmentPlan" rows="5" maxlength="1800"></textarea></label><div class="admin-actions"><button class="btn btn-olive" type="submit">부서/채용 계획 저장</button><a class="btn btn-dark" data-career-preview href="../careers/flight-operations/" target="_blank" rel="noopener">현재 부서 미리보기</a></div><p data-career-admin-status style="margin-top:12px;color:#666">부서를 선택하면 현재 저장된 내용을 불러옵니다.</p></form>`;const first=document.querySelector('.admin-panel');if(first)first.insertAdjacentElement('beforebegin',panel);else consoleHost.appendChild(panel);form=panel.querySelector('[data-career-form]');statusEl=panel.querySelector('[data-career-admin-status]');form.elements.department.addEventListener('change',()=>loadDepartment(form.elements.department.value));form.addEventListener('submit',saveDepartment);return panel;}
function setStatus(text,error=false){if(!statusEl)return;statusEl.textContent=text;statusEl.style.color=error?'#b73333':'#2c7a45';}
function fill(data){if(!form||!data)return;form.elements.koreanTitle.value=data.koreanTitle||'';form.elements.summary.value=data.summary||'';form.elements.duties.value=(data.duties||[]).join('\n');form.elements.hiringStatus.value=data.hiringStatus||'채용 계획 검토 중';form.elements.recruitmentPeriod.value=data.recruitmentPeriod||'';form.elements.plannedRoles.value=data.plannedRoles||'';form.elements.recruitmentPlan.value=data.recruitmentPlan||'';form.querySelector('[data-career-preview]').href=`../careers/${form.elements.department.value}/`;}
async function loadDepartment(slug){const base=CAREER_DEPARTMENTS[slug];fill(base);setStatus('저장된 내용을 확인하는 중…');try{const snap=await getDoc(doc(db,'notices',careerDocId(slug)));if(snap.exists())fill(parseCareerNotice(slug,snap.data()));setStatus('현재 부서 정보를 불러왔습니다.');}catch(error){fill(base);setStatus('저장된 데이터가 없어 기본 내용을 표시합니다.',true);}}
async function saveDepartment(event){event.preventDefault();const user=auth.currentUser;if(!isAdmin(user)){setStatus('관리자 권한을 확인할 수 없습니다.',true);return;}const slug=form.elements.department.value;const data={koreanTitle:form.elements.koreanTitle.value.trim(),summary:form.elements.summary.value.trim(),duties:form.elements.duties.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean).slice(0,12),hiringStatus:form.elements.hiringStatus.value,recruitmentPeriod:form.elements.recruitmentPeriod.value.trim(),plannedRoles:form.elements.plannedRoles.value.trim(),recruitmentPlan:form.elements.recruitmentPlan.value.trim()};if(!data.koreanTitle||!data.summary||!data.duties.length){setStatus('부서명, 소개, 주요 업무를 입력해 주세요.',true);return;}const ref=doc(db,'notices',careerDocId(slug));const title=`CAREERS DATA · ${CAREER_DEPARTMENTS[slug].title}`;try{const snap=await getDoc(ref);const common={category:'일반',author:'STELLARIS CAREERS',status:'draft',publishStart:Timestamp.now(),publishEnd:null,title,body:careerNoticePayload(data),pinned:false,updatedAt:serverTimestamp()};if(snap.exists())await updateDoc(ref,common);else await setDoc(ref,{...common,views:0,publishedAt:serverTimestamp()});setStatus('부서 소개와 채용 계획을 저장했습니다.');form.querySelector('[data-career-preview]').href=`../careers/${slug}/`;}catch(error){setStatus(`저장 실패: ${String(error?.code||error?.message||error)}`,true);}}
function hideCareerDataFromNoticeManager(){document.querySelectorAll('[data-admin-notice-list] .admin-notice-item').forEach(item=>{const title=item.querySelector('h3')?.textContent||'';if(title.startsWith('CAREERS DATA ·'))item.hidden=true;});}
onAuthStateChanged(auth,user=>{if(!isAdmin(user))return;ensurePanel();loadDepartment(form.elements.department.value);const noticeList=document.querySelector('[data-admin-notice-list]');if(noticeList){hideCareerDataFromNoticeManager();new MutationObserver(hideCareerDataFromNoticeManager).observe(noticeList,{childList:true,subtree:true});}});