(()=>{
'use strict';
const L={
'en-US':{
hero:'Earn Star Miles on domestic and international flights, including Stellaris Group airlines, and enjoy benefits based on your tier.',title:'See your Star Miles at a glance.',body:'Check your balance, member tier, progress to the next tier and recent earning activity.',view:'View my Star Miles',earn:'Star Miles earning rates',domestic:'Domestic',domesticRate:'10 Star Miles per KRW 1,000 of fare',international:'International',internationalRate:'15 Star Miles per KRW 1,000 of fare',bonus:'Bonus miles on premium and higher fares',group:'You can also earn Star Miles when flying Stellaris Group airlines.',tiers:'Tiers and key benefits',tier:'Tier',requirement:'Requirement',benefits:'Key benefits',standard:'Standard',earning:'Mileage earning',silverReq:'20,000 miles',silver:'Priority check-in, extra baggage',goldReq:'50,000 miles',gold:'Lounge access, priority boarding',platReq:'100,000 miles',plat:'Complimentary upgrades, lounge + additional benefits',stellarReq:'200,000 miles',stellar:'Highest tier, top-priority service'},
'en-GB':null,
'zh-CN':{
hero:'搭乘国内线、国际线以及 Stellaris Group 旗下航空公司航班可累积 Star Miles，并享受对应等级权益。',title:'一目了然查看您的 Star Miles。',body:'查看可用里程、会员等级、距离下一等级的进度以及最近累积记录。',view:'查看我的 Star Miles',earn:'Star Miles 累积标准',domestic:'国内线',domesticRate:'每1,000韩元票价累积10 Star Miles',international:'国际线',internationalRate:'每1,000韩元票价累积15 Star Miles',bonus:'高级及更高票价可获得额外奖励里程',group:'搭乘 Stellaris Group 旗下航空公司同样可以累积 Star Miles。',tiers:'等级与主要权益',tier:'等级',requirement:'条件',benefits:'主要权益',standard:'基础',earning:'里程累积',silverReq:'20,000英里',silver:'优先值机、额外行李',goldReq:'50,000英里',gold:'贵宾室、优先登机',platReq:'100,000英里',plat:'免费升舱、贵宾室及更多权益',stellarReq:'200,000英里',stellar:'最高等级、最高优先服务'},
ja:{
hero:'国内線・国際線、さらに Stellaris Group 各社の利用で Star Miles を貯め、会員ランクごとの特典をお楽しみください。',title:'Star Milesをひと目で確認。',body:'保有マイル、会員ランク、次のランクまでの進捗、最近の積算履歴を確認できます。',view:'Star Milesを確認',earn:'Star Miles積算基準',domestic:'国内線',domesticRate:'運賃1,000ウォンにつき10 Star Miles',international:'国際線',internationalRate:'運賃1,000ウォンにつき15 Star Miles',bonus:'プレミアム・上位運賃では追加ボーナスマイル',group:'Stellaris Group各社の利用でもStar Milesを貯められます。',tiers:'会員ランクと主な特典',tier:'ランク',requirement:'条件',benefits:'主な特典',standard:'基本',earning:'マイル積算',silverReq:'20,000マイル',silver:'優先チェックイン、追加手荷物',goldReq:'50,000マイル',gold:'ラウンジ、優先搭乗',platReq:'100,000マイル',plat:'無料アップグレード、ラウンジ＋追加特典',stellarReq:'200,000マイル',stellar:'最高ランク、最優先サービス'},
es:{
hero:'Acumula Star Miles en vuelos nacionales, internacionales y con las aerolíneas de Stellaris Group, y disfruta de ventajas según tu nivel.',title:'Consulta tus Star Miles de un vistazo.',body:'Consulta tu saldo, nivel, progreso al siguiente nivel y actividad reciente.',view:'Ver mis Star Miles',earn:'Criterios de acumulación de Star Miles',domestic:'Nacional',domesticRate:'10 Star Miles por cada 1.000 KRW de tarifa',international:'Internacional',internationalRate:'15 Star Miles por cada 1.000 KRW de tarifa',bonus:'Millas extra en tarifas premium y superiores',group:'También puedes acumular Star Miles al volar con las aerolíneas de Stellaris Group.',tiers:'Niveles y principales ventajas',tier:'Nivel',requirement:'Condición',benefits:'Principales ventajas',standard:'Estándar',earning:'Acumulación de millas',silverReq:'20.000 millas',silver:'Check-in prioritario, equipaje adicional',goldReq:'50.000 millas',gold:'Sala VIP, embarque prioritario',platReq:'100.000 millas',plat:'Mejoras gratuitas, sala VIP y ventajas adicionales',stellarReq:'200.000 millas',stellar:'Nivel máximo, servicio de máxima prioridad'},
fr:{
hero:'Cumulez des Star Miles sur les vols domestiques, internationaux et les compagnies Stellaris Group, puis profitez d’avantages selon votre statut.',title:'Consultez vos Star Miles en un coup d’œil.',body:'Consultez votre solde, votre statut, votre progression vers le statut suivant et vos gains récents.',view:'Voir mes Star Miles',earn:'Barème de cumul Star Miles',domestic:'Domestique',domesticRate:'10 Star Miles par tranche de 1 000 KRW de tarif',international:'International',internationalRate:'15 Star Miles par tranche de 1 000 KRW de tarif',bonus:'Miles bonus supplémentaires sur les tarifs premium et supérieurs',group:'Vous pouvez également cumuler des Star Miles avec les compagnies de Stellaris Group.',tiers:'Statuts et principaux avantages',tier:'Statut',requirement:'Condition',benefits:'Principaux avantages',standard:'Standard',earning:'Cumul de miles',silverReq:'20 000 miles',silver:'Enregistrement prioritaire, bagage supplémentaire',goldReq:'50 000 miles',gold:'Salon, embarquement prioritaire',platReq:'100 000 miles',plat:'Surclassements gratuits, salon et avantages supplémentaires',stellarReq:'200 000 miles',stellar:'Statut maximal, service prioritaire'}};
L['en-GB']=L['en-US'];
const q=s=>document.querySelector(s), set=(s,v)=>{const n=q(s);if(n)n.textContent=v};
function apply(){const lang=localStorage.getItem('stellaris-language')||'ko';if(lang==='ko')return;const d=L[lang]||L['en-US'];
set('.page-hero-grid>p',d.hero);set('.statement-box h2',d.title);set('.statement-box h2 + p',d.body);set('.statement-box .btn',d.view);set('#earn h2',d.earn);
const stats=document.querySelectorAll('#earn .stat-grid article');if(stats[0]){stats[0].querySelector('span').textContent=d.domestic;stats[0].querySelector('p').textContent=d.domesticRate}if(stats[1]){stats[1].querySelector('span').textContent=d.international;stats[1].querySelector('p').textContent=d.internationalRate}if(stats[2])stats[2].querySelector('p').textContent=d.bonus;
set('#earn .note',d.group);set('#tiers h2',d.tiers);const rows=document.querySelectorAll('#tiers .tier-row');if(rows[0]){rows[0].children[0].textContent=d.tier;rows[0].children[1].textContent=d.requirement;rows[0].children[2].textContent=d.benefits}const vals=[[d.standard,d.earning],[d.silverReq,d.silver],[d.goldReq,d.gold],[d.platReq,d.plat],[d.stellarReq,d.stellar]];rows.forEach((r,i)=>{if(i&&vals[i-1]){r.children[1].textContent=vals[i-1][0];r.children[2].textContent=vals[i-1][1]}})}
window.addEventListener('stellaris:languagechange',apply);setTimeout(apply,0);
})();